import { q } from './builder'

/** Questões autorais — Macrotemas 3 e 4. */
export const BANCO_M34 = [
  q('q-suit-01', {
    c: 'c-suitability', tipo: 'conceitual', dif: 'facil',
    hab: 'Listar as dimensões do suitability',
    e: 'A verificação de adequação (suitability) deve considerar:',
    alt: [
      ['Objetivos de investimento, situação financeira e conhecimento do cliente.', true, 'Correta. São as três dimensões exigidas pela regulação.'],
      ['Renda, idade e estado civil do cliente.', false, 'São dados cadastrais úteis, mas não são as três dimensões do suitability.'],
      ['Apenas a tolerância a risco declarada pelo cliente.', false, 'Tolerância a risco isolada não cobre objetivos nem conhecimento.'],
      ['Histórico de crédito e score do cliente.', false, 'Score de crédito diz respeito a empréstimo, não a adequação de investimento.'],
    ],
    exp: 'Objetivo (para quê), situação financeira (aguenta perder?) e conhecimento (entende o produto?).',
    tags: ['suitability', 'perfil'],
  }),
  q('q-suit-02', {
    c: 'c-suitability', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Agir diante de operação inadequada ao perfil',
    ctx: 'Cliente de perfil conservador, com perfil vigente, solicita por iniciativa própria a aplicação de metade do patrimônio em um fundo de ações.',
    e: 'A conduta correta é:',
    alt: [
      ['Alertar sobre a inadequação e, se o cliente mantiver a decisão, obter declaração expressa de ciência antes de executar.', true, 'Correta. Alerta documentado é o procedimento previsto para operação inadequada.'],
      ['Atualizar o questionário de perfil para arrojado e executar a operação.', false, 'Alterar o perfil para viabilizar a venda é falta grave.'],
      ['Executar sem observações, pois a iniciativa foi do cliente.', false, 'A iniciativa do cliente não dispensa o alerta sobre a inadequação.'],
      ['Recusar terminantemente a operação em qualquer hipótese.', false, 'A regra não é proibir, e sim alertar e documentar a ciência.'],
    ],
    exp: 'Inadequação não bloqueia a operação — obriga a alertar e registrar a ciência do cliente.',
    tags: ['suitability', 'conduta'],
  }),
  q('q-suit-03', {
    c: 'c-suitability', tipo: 'verdadeiro_falso', dif: 'media',
    hab: 'Avaliar validade do perfil',
    e: 'Avalie: "Com o perfil do cliente vencido, o profissional pode recomendar produtos de baixo risco, mas não de alto risco."',
    alt: [
      ['Falso — sem perfil vigente não se faz recomendação, independentemente do risco do produto.', true, 'Correta. A vigência do perfil é condição para qualquer recomendação.'],
      ['Verdadeiro — o risco baixo dispensa a atualização.', false, 'Não há dispensa por nível de risco; o perfil precisa estar vigente.'],
      ['Verdadeiro — desde que o cliente assine termo de ciência.', false, 'O termo de ciência serve para inadequação, não para suprir perfil vencido.'],
      ['Falso — mas a recomendação é permitida se autorizada pelo gerente regional.', false, 'Não existe autorização hierárquica que substitua o perfil vigente.'],
    ],
    exp: 'Perfil vencido = sem recomendação. A regra não gradua por risco do produto.',
    tags: ['suitability', 'perfil'],
  }),
  q('q-conf-01', {
    c: 'c-conflito', tipo: 'conceitual', dif: 'facil',
    hab: 'Identificar a conduta esperada diante de conflito',
    e: 'Diante de um conflito de interesses potencial, o profissional deve:',
    alt: [
      ['Divulgar o conflito ao cliente de forma clara e prévia.', true, 'Correta. Transparência prévia é o mecanismo previsto para administrar o conflito.'],
      ['Omitir o conflito para não gerar desconfiança.', false, 'Omitir é justamente o que caracteriza a infração.'],
      ['Encerrar o relacionamento com o cliente.', false, 'Encerrar não é exigido; o dever é informar.'],
      ['Comunicar o conflito somente à área de compliance.', false, 'Comunicar internamente não substitui informar o cliente.'],
    ],
    exp: 'Conflito não se elimina — se administra com informação clara e prévia.',
    tags: ['etica', 'conflito'],
  }),
  q('q-conf-02', {
    c: 'c-conflito', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Avaliar conduta sob pressão comercial',
    ctx: 'O gerente está a duas vendas de bater a meta trimestral. Um cliente conservador procura orientação sobre onde aplicar a reserva de emergência.',
    e: 'A conduta correta é:',
    alt: [
      ['Recomendar produto compatível com liquidez e baixo risco, mesmo que não conte para a meta.', true, 'Correta. Reserva de emergência exige liquidez e baixo risco; o interesse do cliente prevalece.'],
      ['Oferecer o produto da campanha, já que o cliente pode aceitar.', false, 'Usar a meta como critério de recomendação inverte a prioridade e configura infração.'],
      ['Oferecer o produto da campanha e mencionar rapidamente os riscos.', false, 'Menção superficial não corrige uma recomendação inadequada.'],
      ['Deixar o cliente escolher sozinho, sem recomendar nada.', false, 'Abster-se de orientar não cumpre o dever de atendimento adequado.'],
    ],
    exp: 'A recomendação é julgada no momento em que é feita. Meta comercial nunca é critério de adequação.',
    tags: ['etica', 'conflito', 'suitability'],
  }),
  q('q-conf-03', {
    c: 'c-conflito', tipo: 'verdadeiro_falso', dif: 'dificil',
    hab: 'Avaliar conduta pelo processo e não pelo resultado',
    e: 'Avalie: "Se o investimento recomendado de forma inadequada acabou gerando lucro ao cliente, não houve infração."',
    alt: [
      ['Falso — a conduta é avaliada no momento da recomendação, e não pelo resultado obtido.', true, 'Correta. Resultado favorável não convalida recomendação inadequada.'],
      ['Verdadeiro — sem prejuízo não há infração.', false, 'A infração é de conduta e independe de dano financeiro.'],
      ['Verdadeiro — desde que o cliente não reclame.', false, 'A ausência de reclamação não afasta a infração.'],
      ['Falso — mas a penalidade é sempre reduzida à metade quando há lucro.', false, 'Não existe essa regra de redução automática.'],
    ],
    exp: 'Regra central da ética: julga-se a decisão, não a sorte. Sorte não é atenuante.',
    tags: ['etica', 'conduta'],
  }),
  q('q-of-01', {
    c: 'c-openfinance', tipo: 'conceitual', dif: 'facil',
    hab: 'Reconhecer o papel do consentimento no Open Finance',
    e: 'No Open Finance, o compartilhamento de dados do cliente exige:',
    alt: [
      ['Consentimento explícito, com finalidade e prazo definidos, revogável a qualquer momento.', true, 'Correta. O consentimento é a condição do compartilhamento.'],
      ['Apenas autorização prévia do Banco Central à instituição.', false, 'A autorização da instituição não substitui o consentimento do cliente.'],
      ['Contrato de adesão assinado no momento da abertura de conta.', false, 'Consentimento genérico e antecipado não atende ao requisito de finalidade específica.'],
      ['Decisão judicial, por envolver sigilo bancário.', false, 'Não é necessária decisão judicial quando há consentimento do titular.'],
    ],
    exp: 'A palavra-chave do Open Finance é consentimento: explícito, específico, com prazo e revogável.',
    tags: ['open-finance', 'consentimento'],
  }),
  q('q-of-02', {
    c: 'c-openfinance', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Responder a cliente que recusa aderir ao Open Finance',
    ctx: 'Um cliente informa que não deseja compartilhar seus dados no Open Finance.',
    e: 'A conduta correta é:',
    alt: [
      ['Respeitar a recusa, sem qualquer restrição ao atendimento ou aos produtos oferecidos.', true, 'Correta. A adesão é voluntária e a recusa não pode gerar prejuízo ao cliente.'],
      ['Explicar que sem o compartilhamento o banco não pode oferecer crédito.', false, 'Condicionar produto à adesão é prática vedada.'],
      ['Registrar a recusa e reduzir o limite de crédito por precaução.', false, 'Penalizar a recusa contraria o caráter voluntário da adesão.'],
      ['Aderir em nome do cliente e informá-lo depois.', false, 'Consentimento não pode ser presumido nem dado por terceiro.'],
    ],
    exp: 'Adesão voluntária significa que a recusa é neutra: não pode custar nada ao cliente.',
    tags: ['open-finance', 'conduta'],
  }),
  q('q-asg-01', {
    c: 'c-asg', tipo: 'conceitual', dif: 'facil',
    hab: 'Identificar os pilares ASG',
    e: 'Os três pilares do ASG são:',
    alt: [
      ['Ambiental, Social e Governança.', true, 'Correta. É a tradução direta da sigla ESG.'],
      ['Ambiental, Sustentável e Gerencial.', false, 'A sigla não corresponde a esses termos.'],
      ['Acionário, Social e Gerencial.', false, 'Não existe pilar "acionário" no conceito ASG.'],
      ['Ambiental, Setorial e Governança.', false, 'O pilar do meio é Social, não Setorial.'],
    ],
    exp: 'A = Ambiental, S = Social, G = Governança. O G é o mais subestimado e o que mais destrói valor quando falha.',
    tags: ['asg', 'sustentabilidade'],
  }),
  q('q-asg-02', {
    c: 'c-asg', tipo: 'aplicacao', dif: 'media',
    hab: 'Identificar greenwashing',
    ctx: 'Um fundo usa a palavra "sustentável" no nome, mas não divulga metodologia de seleção, critérios objetivos nem métricas de acompanhamento.',
    e: 'A situação caracteriza:',
    alt: [
      ['Greenwashing, com violação do dever de prestar informação clara ao investidor.', true, 'Correta. Rótulo sem substância verificável engana o investidor.'],
      ['Estratégia legítima de gestão ativa protegida por sigilo comercial.', false, 'Sigilo de estratégia não dispensa a divulgação dos critérios que justificam o rótulo.'],
      ['Enquadramento automático como fundo ASG por adotar o termo.', false, 'O rótulo não se autolegitima pelo uso do nome.'],
      ['Prática irrelevante, pois o nome do fundo é apenas comercial.', false, 'O nome comunica ao investidor e por isso é regulado.'],
    ],
    exp: 'Se não há metodologia divulgada e verificável, o rótulo é propaganda — e isso é infração de conduta.',
    tags: ['asg', 'greenwashing', 'etica'],
  }),
  q('q-asg-03', {
    c: 'c-asg', tipo: 'verdadeiro_falso', dif: 'dificil',
    hab: 'Avaliar afirmações sobre retorno de fundos ASG',
    e: 'Avalie: "Fundos que adotam critérios ASG garantem retorno superior aos demais no longo prazo."',
    alt: [
      ['Falso — ASG é uma dimensão adicional de análise de risco, e não garantia de retorno.', true, 'Correta. Nenhum critério de seleção garante retorno; prometer isso é infração.'],
      ['Verdadeiro — há garantia regulatória de desempenho superior.', false, 'Não existe garantia regulatória de desempenho para nenhum tipo de fundo.'],
      ['Verdadeiro — desde que o fundo seja certificado por entidade independente.', false, 'Certificação atesta metodologia, não retorno futuro.'],
      ['Falso — mas o retorno superior é assegurado nos fundos de infraestrutura.', false, 'Nenhuma categoria de fundo assegura retorno.'],
    ],
    exp: 'Prometer ou sugerir retorno garantido é vedado em qualquer contexto — inclusive no ASG.',
    tags: ['asg', 'conduta', 'risco'],
  }),
] as const
