import { q } from './builder'

/** Questões autorais — Macrotema 2 (Produtos). Bloco de maior peso. */
export const BANCO_M2 = [
  q('q-rf-01', {
    c: 'c-rf-base', tipo: 'conceitual', dif: 'facil',
    hab: 'Classificar títulos por tipo de rentabilidade',
    e: 'Um título que remunera "IPCA + 6% ao ano" é classificado como:',
    alt: [
      ['Híbrido, pois combina índice de preços com taxa real.', true, 'Correta. Parte pós-fixada (IPCA) somada a uma taxa real prefixada.'],
      ['Prefixado, pois a taxa de 6% é conhecida.', false, 'Só a parcela real é prefixada; o IPCA é desconhecido na aplicação.'],
      ['Pós-fixado puro, pois depende da inflação.', false, 'Pós-fixado puro não teria a taxa real fixa somada.'],
      ['Indexado ao CDI.', false, 'O indexador é o IPCA, não o CDI.'],
    ],
    exp: 'Híbrido = índice de preços + taxa real. É o formato que protege o poder de compra.',
    tags: ['renda-fixa', 'ipca', 'hibrido'],
  }),
  q('q-rf-02', {
    c: 'c-rf-base', tipo: 'aplicacao', dif: 'media',
    hab: 'Relacionar variação de juros e preço do título',
    e: 'A taxa de juros da economia sobe de forma inesperada. O preço de mercado de um título prefixado já emitido tende a:',
    alt: [
      ['Cair, pois passa a pagar menos que os títulos novos.', true, 'Correta. A relação entre juros e preço é sempre inversa.'],
      ['Subir, pois acompanha a alta dos juros.', false, 'Quem acompanha a alta é o pós-fixado, não o prefixado já emitido.'],
      ['Permanecer estável até o vencimento.', false, 'O preço de mercado oscila diariamente por marcação a mercado.'],
      ['Cair somente se o emissor for privado.', false, 'A marcação a mercado independe de o emissor ser público ou privado.'],
    ],
    exp: 'Juros sobem → títulos novos pagam mais → o antigo precisa ficar mais barato para competir.',
    tags: ['renda-fixa', 'marcacao-mercado', 'prefixado'],
  }),
  q('q-rf-03', {
    c: 'c-rf-base', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Recomendar o indexador conforme o cenário',
    ctx: 'Um cliente tem receio de que a inflação corroa o valor da reserva que ele guarda para uma compra daqui a 8 anos.',
    e: 'O título mais aderente a esse objetivo é:',
    alt: [
      ['Um título híbrido atrelado ao IPCA, com vencimento próximo ao prazo do objetivo.', true, 'Correta. Garante ganho real acima da inflação no horizonte desejado.'],
      ['Um prefixado longo, para travar a taxa mais alta.', false, 'O prefixado não protege da inflação: se ela subir muito, o ganho real desaparece.'],
      ['Um pós-fixado ao CDI, com liquidez diária.', false, 'Acompanha juros, mas não garante ganho acima da inflação no período.'],
      ['Poupança, por ser isenta de imposto de renda.', false, 'A isenção não resolve o problema: a poupança pode render abaixo da inflação.'],
    ],
    exp: 'Objetivo declarado é proteger o poder de compra. Só o híbrido IPCA+ entrega ganho real contratado.',
    tags: ['renda-fixa', 'ipca', 'suitability'],
  }),
  q('q-fgc-01', {
    c: 'c-fgc', tipo: 'multipla_escolha', dif: 'facil',
    hab: 'Identificar produtos cobertos pelo FGC',
    e: 'Qual dos produtos abaixo NÃO conta com cobertura do FGC?',
    alt: [
      ['CRA — Certificado de Recebíveis do Agronegócio.', true, 'Correta. É emitido por securitizadora, não por instituição financeira.'],
      ['CDB — Certificado de Depósito Bancário.', false, 'CDB é emitido por banco e tem cobertura.'],
      ['LCI — Letra de Crédito Imobiliário.', false, 'LCI é emitida por banco e tem cobertura.'],
      ['Caderneta de poupança.', false, 'A poupança é coberta pelo FGC.'],
    ],
    exp: 'A regra prática: emissor banco → FGC. Emissor securitizadora ou empresa → sem FGC.',
    tags: ['fgc', 'renda-fixa', 'garantias'],
  }),
  q('q-fgc-02', {
    c: 'c-fgc', tipo: 'calculo', dif: 'media',
    hab: 'Calcular o valor coberto pelo FGC',
    ctx: 'Um investidor mantém, no mesmo conglomerado financeiro, R$ 180.000 em CDB e R$ 120.000 em LCI, ambos com juros já computados.',
    e: 'Em caso de liquidação da instituição, o valor coberto pelo FGC será de:',
    alt: [
      ['R$ 250.000', true, 'Correta. O total é R$ 300.000, mas o limite por CPF por conglomerado é R$ 250.000.'],
      ['R$ 300.000', false, 'Ultrapassa o limite: R$ 50.000 ficam descobertos.'],
      ['R$ 180.000', false, 'O limite não se aplica a um único produto — soma-se tudo do conglomerado até R$ 250 mil.'],
      ['R$ 500.000', false, 'Não existe limite dobrado por haver dois produtos distintos.'],
    ],
    exp: 'Soma tudo que é coberto no conglomerado e aplica o teto de R$ 250 mil. O excedente vira crédito na massa.',
    tags: ['fgc', 'calculo', 'limites'],
  }),
  q('q-fgc-03', {
    c: 'c-fgc', tipo: 'comparacao', dif: 'dificil',
    hab: 'Comparar risco de crédito entre produtos',
    e: 'Comparando um CDB de banco médio e um título público federal quanto ao risco de crédito, é correto afirmar:',
    alt: [
      ['O título público tem menor risco de crédito, ainda que não conte com FGC.', true, 'Correta. Risco soberano é o menor da economia; o FGC não é necessário nesse caso.'],
      ['O CDB tem menor risco porque conta com FGC.', false, 'O FGC reduz o risco, mas não o torna menor que o do próprio governo emissor da moeda.'],
      ['Ambos têm o mesmo risco, pois os dois têm garantia.', false, 'O título público não tem FGC; as garantias são de naturezas diferentes.'],
      ['O título público tem maior risco porque não tem FGC.', false, 'Ausência de FGC não significa maior risco — significa outro tipo de garantia.'],
    ],
    exp: 'Ter FGC não é o mesmo que ter menos risco. O soberano dispensa o FGC justamente por ser a referência de menor risco.',
    tags: ['fgc', 'risco-credito', 'tesouro'],
  }),
  q('q-trib-01', {
    c: 'c-rf-tributacao', tipo: 'calculo', dif: 'media',
    hab: 'Aplicar a tabela regressiva de IR',
    ctx: 'Aplicação de R$ 20.000 em CDB, resgatada após 400 dias, com valor bruto final de R$ 24.000.',
    e: 'O imposto de renda devido é de:',
    alt: [
      ['R$ 700', true, 'Correta. Rendimento de R$ 4.000 × 17,5% (faixa de 361 a 720 dias) = R$ 700.'],
      ['R$ 800', false, 'Usaria 20%, alíquota da faixa de 181 a 360 dias.'],
      ['R$ 600', false, 'Usaria 15%, alíquota aplicável apenas acima de 720 dias.'],
      ['R$ 4.200', false, 'Aplicaria a alíquota sobre o valor total resgatado, e não sobre o rendimento.'],
    ],
    exp: 'Base de cálculo é sempre o rendimento (R$ 24.000 − R$ 20.000). 400 dias cai na faixa de 17,5%.',
    tags: ['tributacao', 'calculo', 'renda-fixa'],
  }),
  q('q-trib-02', {
    c: 'c-rf-tributacao', tipo: 'multipla_escolha', dif: 'facil',
    hab: 'Reconhecer produtos isentos de IR para PF',
    e: 'São isentos de imposto de renda para pessoa física:',
    alt: [
      ['LCI, LCA, CRI e CRA.', true, 'Correta. Todos gozam de isenção para a pessoa física.'],
      ['CDB, LCI e debênture comum.', false, 'CDB e debênture comum são tributados pela tabela regressiva.'],
      ['Tesouro Selic e Tesouro IPCA+.', false, 'Títulos públicos são tributados normalmente.'],
      ['Fundos de renda fixa e LCA.', false, 'Fundos de renda fixa são tributados; a LCA é isenta.'],
    ],
    exp: 'Grupo dos isentos para PF: LCI, LCA, CRI, CRA, poupança e debênture incentivada.',
    tags: ['tributacao', 'isencao'],
  }),
  q('q-trib-03', {
    c: 'c-rf-tributacao', tipo: 'comparacao', dif: 'dificil',
    hab: 'Comparar retorno líquido entre produto isento e tributado',
    ctx: 'Prazo de 2 anos. Opção A: CDB a 100% do CDI (tributado, alíquota de 15%). Opção B: LCI a 88% do CDI (isenta).',
    e: 'Considerando apenas a tributação, qual conclusão está correta?',
    alt: [
      ['A LCI é melhor, pois 88% líquidos superam 85% do CDI que sobram do CDB após o IR.', true, 'Correta. 100% × (1 − 0,15) = 85% líquidos, abaixo dos 88% da LCI.'],
      ['O CDB é melhor, pois paga 100% do CDI.', false, 'Comparar bruto com líquido é o erro clássico; após IR o CDB rende 85%.'],
      ['São equivalentes, pois a diferença de 12 pontos compensa exatamente o imposto.', false, 'A diferença é de 12 pontos, mas o IR consome 15 — não se equivalem.'],
      ['Não é possível comparar sem saber o valor aplicado.', false, 'A comparação é percentual e independe do valor aplicado.'],
    ],
    exp: 'Sempre compare líquido com líquido. Aqui, 85% (CDB pós-IR) contra 88% (LCI isenta).',
    tags: ['tributacao', 'comparacao', 'lci'],
  }),
  q('q-fundos-01', {
    c: 'c-fundos', tipo: 'conceitual', dif: 'facil',
    hab: 'Calcular o valor da cota',
    e: 'O valor da cota de um fundo de investimento é obtido por:',
    alt: [
      ['Patrimônio líquido dividido pelo número de cotas.', true, 'Correta. É a definição de cota.'],
      ['Valor aplicado dividido pelo número de cotistas.', false, 'O número de cotistas não entra no cálculo.'],
      ['Rentabilidade acumulada multiplicada pela taxa de administração.', false, 'Isso não define o valor da cota.'],
      ['Patrimônio bruto dividido pelo número de cotistas.', false, 'Usa-se o patrimônio líquido e o número de cotas, não de cotistas.'],
    ],
    exp: 'Cota = PL ÷ nº de cotas. Note: cotas, não cotistas — um cotista pode ter muitas cotas.',
    tags: ['fundos', 'cota'],
  }),
  q('q-fundos-02', {
    c: 'c-fundos', tipo: 'conceitual', dif: 'media',
    hab: 'Distinguir administrador de gestor',
    e: 'No funcionamento de um fundo de investimento, o GESTOR é responsável por:',
    alt: [
      ['Decidir a compra e a venda dos ativos da carteira.', true, 'Correta. A decisão de investimento é a função do gestor.'],
      ['Responder perante a CVM e os cotistas pelo funcionamento do fundo.', false, 'Essa é a responsabilidade do administrador.'],
      ['Guardar e liquidar os ativos do fundo.', false, 'Guarda e liquidação são do custodiante.'],
      ['Distribuir as cotas ao público investidor.', false, 'A distribuição é do distribuidor.'],
    ],
    exp: 'Gestor decide onde investir. Administrador responde legalmente. São papéis distintos e a banca cobra a diferença.',
    tags: ['fundos', 'prestadores'],
  }),
  q('q-fundos-03', {
    c: 'c-fundos', tipo: 'aplicacao', dif: 'dificil',
    hab: 'Aplicar a regra da linha d\'água',
    ctx: 'Um fundo cobrou taxa de performance no primeiro semestre. No semestre seguinte, a cota caiu 5% e ficou abaixo do benchmark.',
    e: 'Sobre a cobrança de taxa de performance no semestre seguinte:',
    alt: [
      ['Não pode ser cobrada até que o fundo recupere o prejuízo e volte a superar o benchmark.', true, 'Correta. É exatamente a regra da linha d\'água, que impede cobrança dupla pelo mesmo ganho.'],
      ['Pode ser cobrada normalmente, pois a cobrança é semestral.', false, 'A periodicidade mínima não autoriza cobrar sobre ganho ainda não recuperado.'],
      ['Deve ser devolvida ao cotista a taxa cobrada no semestre anterior.', false, 'Não há devolução retroativa; a regra apenas suspende novas cobranças.'],
      ['Pode ser cobrada pela metade, proporcionalmente à queda.', false, 'Não existe cobrança proporcional nessa situação.'],
    ],
    exp: 'Linha d\'água: o fundo precisa voltar ao nível anterior antes de cobrar performance de novo.',
    tags: ['fundos', 'taxa-performance', 'linha-dagua'],
  }),
  q('q-fundos-04', {
    c: 'c-fundos', tipo: 'verdadeiro_falso', dif: 'media',
    hab: 'Avaliar afirmações sobre rentabilidade divulgada',
    e: 'Avalie: "A rentabilidade divulgada por um fundo já está líquida da taxa de administração."',
    alt: [
      ['Verdadeiro — a taxa é provisionada diariamente e já afeta o valor da cota.', true, 'Correta. Por isso não se deve descontá-la de novo da rentabilidade informada.'],
      ['Falso — a taxa é cobrada apenas no resgate.', false, 'A taxa de administração é provisionada diariamente, não cobrada só no resgate.'],
      ['Verdadeiro — e também já está líquida de imposto de renda.', false, 'O IR não está descontado da cota divulgada; incide no resgate ou via come-cotas.'],
      ['Falso — a rentabilidade divulgada é sempre bruta.', false, 'A cota reflete o patrimônio já deduzido da taxa de administração.'],
    ],
    exp: 'A cota nasce líquida de taxa de administração. Descontá-la outra vez é contar duas vezes.',
    tags: ['fundos', 'taxas'],
  }),
  q('q-acoes-01', {
    c: 'c-acoes', tipo: 'conceitual', dif: 'facil',
    hab: 'Distinguir ON de PN',
    e: 'A ação preferencial (PN) caracteriza-se por:',
    alt: [
      ['Ter preferência na distribuição de proventos e no reembolso de capital, em regra sem direito a voto.', true, 'Correta. É a troca típica: preferência econômica no lugar do voto.'],
      ['Garantir rentabilidade mínima ao acionista.', false, 'Nenhuma ação garante rentabilidade.'],
      ['Dar direito a voto em todas as assembleias.', false, 'O direito a voto é característico da ordinária (ON).'],
      ['Contar com cobertura do FGC.', false, 'Ações não têm cobertura do FGC.'],
    ],
    exp: 'ON vota. PN recebe primeiro. Nenhuma das duas garante retorno.',
    tags: ['acoes', 'renda-variavel'],
  }),
  q('q-acoes-02', {
    c: 'c-acoes', tipo: 'calculo', dif: 'media',
    hab: 'Calcular o retorno total do acionista',
    ctx: 'Investidor compra 500 ações a R$ 18,00. Durante o ano recebe R$ 0,90 por ação em proventos e vende tudo a R$ 20,50.',
    e: 'O retorno total bruto da operação, em reais, foi de:',
    alt: [
      ['R$ 1.700,00', true, 'Correta. Valorização: 500 × R$ 2,50 = R$ 1.250. Proventos: 500 × R$ 0,90 = R$ 450. Total R$ 1.700.'],
      ['R$ 1.250,00', false, 'Considerou apenas a valorização e ignorou os proventos.'],
      ['R$ 450,00', false, 'Considerou apenas os proventos e ignorou a valorização.'],
      ['R$ 2.150,00', false, 'Soma incorreta — provavelmente somou o preço de venda em vez da diferença.'],
    ],
    exp: 'Retorno do acionista = valorização + proventos. Esquecer um dos dois é o erro mais comum.',
    tags: ['acoes', 'calculo', 'proventos'],
  }),
  q('q-acoes-03', {
    c: 'c-acoes', tipo: 'conceitual', dif: 'dificil',
    hab: 'Reconhecer o direito de tag along',
    e: 'O tag along assegura ao acionista minoritário ordinário, na alienação do controle da companhia:',
    alt: [
      ['O direito de vender suas ações por, no mínimo, 80% do valor pago por ação ao controlador.', true, 'Correta. É o piso legal, que pode ser ampliado conforme o segmento de listagem.'],
      ['O direito de vetar a operação de venda do controle.', false, 'Tag along dá direito de saída, não poder de veto.'],
      ['O direito de receber dividendos em dobro no exercício da venda.', false, 'Não há relação entre tag along e dobro de dividendos.'],
      ['O direito de converter suas ações em preferenciais.', false, 'Tag along não envolve conversão de classe.'],
    ],
    exp: 'Tag along é direito de saída em condições próximas às do controlador. Mínimo legal de 80% para ON.',
    tags: ['acoes', 'governanca', 'tag-along'],
  }),
  q('q-prev-01', {
    c: 'c-previdencia', tipo: 'situacao_pratica', dif: 'facil',
    hab: 'Recomendar PGBL ou VGBL pelo perfil fiscal',
    ctx: 'Cliente declara imposto de renda no modelo simplificado e não pretende mudar.',
    e: 'O plano de previdência mais adequado é:',
    alt: [
      ['VGBL, pois ele não aproveitaria a dedução do PGBL e o IR incidirá apenas sobre o rendimento.', true, 'Correta. Sem declaração completa, o benefício do PGBL não se realiza.'],
      ['PGBL, para deduzir até 12% da renda bruta.', false, 'A dedução só existe para quem declara no modelo completo.'],
      ['PGBL, pois tem tributação menor no resgate.', false, 'É o oposto: no PGBL o IR incide sobre o valor total resgatado.'],
      ['Indiferente, pois a tributação é idêntica nos dois.', false, 'A base de cálculo no resgate é diferente em cada um.'],
    ],
    exp: 'Declaração simplificada ou isento → VGBL. Declaração completa + INSS → PGBL.',
    tags: ['previdencia', 'pgbl', 'vgbl', 'suitability'],
  }),
  q('q-prev-02', {
    c: 'c-previdencia', tipo: 'comparacao', dif: 'media',
    hab: 'Comparar a base de cálculo do IR entre PGBL e VGBL',
    e: 'No resgate, o imposto de renda incide sobre:',
    alt: [
      ['O valor total no PGBL e apenas sobre o rendimento no VGBL.', true, 'Correta. É a contrapartida da dedução obtida no PGBL durante a fase de acumulação.'],
      ['Apenas o rendimento em ambos.', false, 'No PGBL a base é o valor total resgatado.'],
      ['O valor total em ambos.', false, 'No VGBL a base é somente o rendimento.'],
      ['Apenas o rendimento no PGBL e o valor total no VGBL.', false, 'Está invertido: quem deduziu na acumulação (PGBL) paga sobre o total; quem não deduziu (VGBL) paga só sobre o ganho.'],
    ],
    exp: 'Quem deduziu na entrada (PGBL) paga na saída sobre tudo. Quem não deduziu (VGBL) paga só sobre o ganho.',
    tags: ['previdencia', 'tributacao'],
  }),
  q('q-prev-03', {
    c: 'c-previdencia', tipo: 'case', dif: 'dificil',
    hab: 'Analisar recomendação de previdência com múltiplas variáveis',
    ctx: 'Cliente de 38 anos, CLT, contribui ao INSS, declara no modelo completo, renda tributável de R$ 240.000/ano. Pretende resgatar apenas na aposentadoria, daqui a mais de 20 anos, e já contribui com R$ 15.000/ano em outro PGBL.',
    e: 'A recomendação mais adequada é:',
    alt: [
      ['PGBL com regime regressivo, respeitando o limite total de 12% da renda bruta anual — ou seja, no máximo mais R$ 13.800 em contribuições dedutíveis.', true, 'Correta. 12% de R$ 240.000 = R$ 28.800; já aporta R$ 15.000, restando R$ 13.800. O horizonte longo favorece o regime regressivo.'],
      ['PGBL com regime progressivo, sem limite de aporte dedutível.', false, 'O limite de 12% existe independentemente do regime, e o horizonte longo favorece o regressivo.'],
      ['VGBL com regime regressivo, pois o prazo é longo.', false, 'O cliente declara no completo e contribui ao INSS — desperdiçaria a dedução do PGBL.'],
      ['PGBL sem limite, pois o limite de 12% vale por plano e não por contribuinte.', false, 'O limite de 12% é do contribuinte, somando todos os planos, não de cada plano isoladamente.'],
    ],
    exp: 'Duas armadilhas aqui: o limite de 12% é por contribuinte (soma todos os PGBLs) e o horizonte longo aponta para o regime regressivo.',
    tags: ['previdencia', 'pgbl', 'calculo', 'case'],
  }),
] as const
