import { q } from './builder'

/**
 * Questões autorais — microtema 1.3 (Operações do mercado financeiro).
 *
 * É o bloco quantitativo do programa, e por isso concentra o tipo `calculo`,
 * que antes tinha três itens no banco inteiro. Todo resultado numérico daqui
 * foi conferido por cálculo antes de virar alternativa — inclusive os
 * distratores, que são erros PLAUSÍVEIS (regime trocado, taxa proporcional no
 * lugar da equivalente, subtração no lugar de Fisher) e não números soltos.
 * Distrator aleatório não ensina nada; distrator que reproduz o erro comum
 * transforma a questão errada em diagnóstico.
 */
export const BANCO_M1_3 = [
  /* ---- c-juros-compostos ------------------------------------------- */
  q('q-jc-01', {
    c: 'c-juros-compostos', tipo: 'calculo', dif: 'facil',
    hab: 'Calcular valor futuro no regime composto',
    e: 'Qual o montante de R$ 1.000 aplicados por 3 anos a 10% ao ano no regime de juros compostos?',
    alt: [
      ['R$ 1.331,00', true, 'Correta. 1.000 × 1,10³ = 1.000 × 1,331.'],
      ['R$ 1.300,00', false, 'Esse é o resultado no regime SIMPLES: R$ 100 por ano, três vezes.'],
      ['R$ 1.310,00', false, 'Não corresponde a nenhum dos dois regimes; parece capitalizar apenas o último ano.'],
      ['R$ 1.100,00', false, 'É o montante de um único ano, não de três.'],
    ],
    exp: 'No regime composto o fator (1 + i) se multiplica a cada período: 1,10 × 1,10 × 1,10 = 1,331.',
    tags: ['juros-compostos', 'valor-futuro', 'calculo'],
  }),
  q('q-jc-02', {
    c: 'c-juros-compostos', tipo: 'calculo', dif: 'media',
    hab: 'Calcular valor presente descontando um fluxo futuro',
    e: 'Quanto vale hoje um recebimento de R$ 10.000 daqui a 2 anos, a uma taxa de desconto de 8% ao ano?',
    alt: [
      ['R$ 8.573,39', true, 'Correta. 10.000 ÷ 1,08² = 10.000 ÷ 1,1664.'],
      ['R$ 8.400,00', false, 'Resulta de descontar 8% duas vezes por subtração, não por divisão.'],
      ['R$ 9.259,26', false, 'É o desconto de apenas um ano: 10.000 ÷ 1,08.'],
      ['R$ 11.664,00', false, 'Esse é o valor FUTURO de R$ 10.000, não o presente. A operação foi invertida.'],
    ],
    exp: 'Trazer a valor presente é dividir pelo fator: VP = VF ÷ (1 + i)^n.',
    tags: ['valor-presente', 'desconto', 'calculo'],
  }),
  q('q-jc-03', {
    c: 'c-juros-compostos', tipo: 'comparacao', dif: 'media',
    hab: 'Comparar os regimes simples e composto',
    e: 'Sobre a comparação entre juros simples e compostos para o mesmo capital, taxa e prazo, é correto afirmar:',
    alt: [
      ['Para n maior que 1 período, o regime composto produz montante maior.', true, 'Correta. A partir do segundo período o juro passa a render sobre juro.'],
      ['O regime composto é sempre maior, qualquer que seja o prazo.', false, 'Em n = 1 os dois empatam, e em frações de período o simples supera o composto.'],
      ['O regime simples é maior no longo prazo, por acumular menos base.', false, 'É o contrário: a base fixa do simples faz o montante crescer em linha reta e ficar para trás.'],
      ['Os dois regimes produzem o mesmo montante em qualquer prazo.', false, 'Só coincidem em exatamente um período.'],
    ],
    exp: 'Os regimes empatam em n = 1. Acima disso o composto ganha; abaixo — frações de período — o simples ganha.',
    tags: ['juros-compostos', 'juros-simples', 'comparacao'],
  }),
  q('q-jc-04', {
    c: 'c-juros-compostos', tipo: 'calculo', dif: 'media',
    hab: 'Aplicar a capitalização composta em períodos mensais',
    ctx: 'Um investidor aplica R$ 5.000 por 6 meses a 1,5% ao mês no regime composto.',
    e: 'Qual o valor aproximado de resgate?',
    alt: [
      ['R$ 5.467,22', true, 'Correta. 5.000 × 1,015⁶ = 5.000 × 1,093443.'],
      ['R$ 5.450,00', false, 'É o regime simples: 5.000 × (1 + 0,015 × 6).'],
      ['R$ 5.075,00', false, 'Corresponde a um único mês de rendimento.'],
      ['R$ 5.900,00', false, 'Superestima; equivaleria a uma taxa perto de 3% ao mês.'],
    ],
    exp: '5.000 × 1,015⁶ = R$ 5.467,22. A diferença de R$ 17,22 para o regime simples é o juro sobre juro dos seis meses.',
    tags: ['juros-compostos', 'calculo', 'mensal'],
  }),
  q('q-jc-05', {
    c: 'c-juros-compostos', tipo: 'conceitual', dif: 'facil',
    hab: 'Reconhecer a exigência de mesma unidade entre taxa e prazo',
    e: 'Para aplicar VF = VP × (1 + i)^n corretamente, é indispensável que:',
    alt: [
      ['A taxa e o número de períodos estejam na mesma unidade de tempo.', true, 'Correta. Taxa mensal exige n em meses; taxa anual exige n em anos.'],
      ['A taxa esteja sempre expressa ao ano.', false, 'A unidade pode ser qualquer uma, desde que o prazo acompanhe.'],
      ['O prazo seja necessariamente um número inteiro.', false, 'A fórmula aceita expoentes fracionários sem problema.'],
      ['O capital inicial seja superior a R$ 1.000.', false, 'O valor do capital não interfere na validade da fórmula.'],
    ],
    exp: 'Usar 12% ao ano com n = 12 meses é o erro mais comum da matéria: ou converte a taxa, ou converte o prazo.',
    tags: ['juros-compostos', 'unidade', 'conceitual'],
  }),
  q('q-jc-06', {
    c: 'c-juros-compostos', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Identificar o regime de capitalização numa oferta comercial',
    ctx: 'Duas aplicações de 24 meses anunciam "1% ao mês". A primeira capitaliza mensalmente; a segunda paga juro simples sobre o valor aplicado.',
    e: 'Sobre o resgate de R$ 1.000 em cada uma, é correto afirmar:',
    alt: [
      ['A primeira devolve mais, porque o juro de cada mês passa a render nos meses seguintes.', true, 'Correta. 1.000 × 1,01²⁴ = R$ 1.269,73 contra R$ 1.240 do regime simples.'],
      ['As duas devolvem o mesmo valor, pois a taxa anunciada é idêntica.', false, 'A taxa é a mesma, mas a base de cálculo não: uma incide sobre o saldo, a outra sobre o valor inicial.'],
      ['A segunda devolve mais, porque não desconta a capitalização.', false, 'Não há desconto por capitalizar; capitalizar aumenta o montante.'],
      ['A comparação é impossível sem conhecer a inflação do período.', false, 'A inflação afeta o ganho REAL, mas o montante nominal já é comparável.'],
    ],
    exp: 'Taxa anunciada igual não significa resgate igual. Perguntar o regime de capitalização é parte da recomendação.',
    tags: ['juros-compostos', 'suitability', 'situacao-pratica'],
  }),

  /* ---- c-taxas-equivalentes ---------------------------------------- */
  q('q-te-01', {
    c: 'c-taxas-equivalentes', tipo: 'calculo', dif: 'media',
    hab: 'Converter taxa nominal em taxa efetiva',
    e: 'Uma taxa nominal de 12% ao ano com capitalização mensal corresponde a qual taxa efetiva anual?',
    alt: [
      ['12,68% ao ano', true, 'Correta. A nominal gera 1% a.m. proporcional; 1,01¹² − 1 = 12,68%.'],
      ['12,00% ao ano', false, 'Esse é o valor nominal anunciado. Ele ignora a capitalização dos onze meses intermediários.'],
      ['11,39% ao ano', false, 'Não corresponde a nenhuma conversão válida a partir de 12% nominais.'],
      ['1,00% ao ano', false, 'Confunde a taxa mensal proporcional com a taxa anual.'],
    ],
    exp: 'Taxa nominal só ganha significado com a frequência de capitalização. Aqui, doze capitalizações de 1% produzem 12,68% efetivos.',
    tags: ['taxa-nominal', 'taxa-efetiva', 'calculo'],
  }),
  q('q-te-02', {
    c: 'c-taxas-equivalentes', tipo: 'calculo', dif: 'dificil',
    hab: 'Calcular a taxa equivalente entre períodos',
    e: 'Qual a taxa mensal EQUIVALENTE a 12% ao ano no regime composto?',
    alt: [
      ['0,9489% ao mês', true, 'Correta. (1,12)^(1/12) − 1 = 0,009489.'],
      ['1,0000% ao mês', false, 'Essa é a taxa PROPORCIONAL (12 ÷ 12), do regime simples. Capitalizada, ela daria 12,68% e não 12%.'],
      ['1,0600% ao mês', false, 'Não decorre de nenhuma conversão de 12% ao ano.'],
      ['0,1200% ao mês', false, 'Divide a taxa por 100 em vez de converter o período.'],
    ],
    exp: 'Equivalente extrai raiz de índice 12; proporcional divide por 12. Os dois números são diferentes justamente porque os regimes são diferentes.',
    tags: ['taxa-equivalente', 'taxa-proporcional', 'calculo'],
  }),
  q('q-te-03', {
    c: 'c-taxas-equivalentes', tipo: 'calculo', dif: 'media',
    hab: 'Converter taxa mensal em taxa anual efetiva',
    e: 'Uma aplicação rende 2% ao mês. Qual a taxa efetiva anual equivalente?',
    alt: [
      ['26,82% ao ano', true, 'Correta. 1,02¹² − 1 = 0,2682.'],
      ['24,00% ao ano', false, 'É a taxa proporcional (2 × 12). Ela ignora a capitalização dos meses intermediários.'],
      ['22,00% ao ano', false, 'Não corresponde a nenhuma conversão de 2% ao mês.'],
      ['12,00% ao ano', false, 'Divide o prazo em vez de capitalizar a taxa.'],
    ],
    exp: 'Quanto maior a taxa mensal, maior a distância entre o número proporcional e o efetivo — aqui, quase 3 pontos.',
    tags: ['taxa-equivalente', 'calculo', 'anualizacao'],
  }),
  q('q-te-04', {
    c: 'c-taxas-equivalentes', tipo: 'conceitual', dif: 'facil',
    hab: 'Distinguir taxa nominal de taxa efetiva',
    e: 'A diferença entre taxa nominal e taxa efetiva é que a nominal:',
    alt: [
      ['É anunciada em um período mas capitalizada em outro, e por isso não informa sozinha o rendimento.', true, 'Correta. Ela só ganha significado acompanhada da frequência de capitalização.'],
      ['Já considera a inflação do período.', false, 'Isso descreve a diferença entre taxa nominal e taxa REAL, que é outro par de conceitos.'],
      ['É sempre maior que a efetiva.', false, 'É o contrário: havendo mais de uma capitalização no período, a efetiva supera a nominal.'],
      ['Se aplica apenas a operações de crédito.', false, 'A distinção vale igualmente para aplicações e para crédito.'],
    ],
    exp: 'Atenção ao vocabulário: "nominal × efetiva" trata de capitalização; "nominal × real" trata de inflação. São eixos distintos.',
    tags: ['taxa-nominal', 'taxa-efetiva', 'conceitual'],
  }),
  q('q-te-05', {
    c: 'c-taxas-equivalentes', tipo: 'situacao_pratica', dif: 'dificil',
    hab: 'Comparar produtos com taxas em períodos diferentes',
    ctx: 'Um cliente compara um fundo que informa 0,95% ao mês com um CDB que informa 12% ao ano efetivos.',
    e: 'Qual comparação está correta?',
    alt: [
      ['São praticamente equivalentes: 0,95% ao mês corresponde a 12,01% ao ano.', true, 'Correta. 1,0095¹² − 1 = 0,1201.'],
      ['O CDB é claramente melhor, pois 0,95 × 12 = 11,4% ao ano.', false, 'Multiplicar por 12 dá a taxa proporcional e subestima o rendimento do fundo.'],
      ['O fundo é muito melhor, pois 0,95% ao mês supera 12% ao ano com folga.', false, 'A vantagem existe, mas é de 0,01 ponto — não é "com folga".'],
      ['A comparação é impossível sem saber o prazo da aplicação.', false, 'Taxas efetivas convertidas para o mesmo período já são comparáveis.'],
    ],
    exp: 'Taxas em períodos diferentes só se comparam depois de convertidas pelo regime composto. O atalho da multiplicação inverteria a conclusão.',
    tags: ['taxa-equivalente', 'comparacao', 'atendimento'],
  }),
  q('q-te-06', {
    c: 'c-taxas-equivalentes', tipo: 'calculo', dif: 'media',
    hab: 'Converter taxa anual em taxa semestral equivalente',
    e: 'Qual a taxa semestral equivalente a 21% ao ano no regime composto?',
    alt: [
      ['10,00% ao semestre', true, 'Correta. (1,21)^(1/2) − 1 = 0,10, pois 1,10 × 1,10 = 1,21.'],
      ['10,50% ao semestre', false, 'É a taxa proporcional (21 ÷ 2), que capitalizada daria 22,10% e não 21%.'],
      ['11,00% ao semestre', false, 'Capitalizada duas vezes daria 23,21%, acima da taxa anual informada.'],
      ['21,00% ao semestre', false, 'Repete a taxa anual sem converter o período.'],
    ],
    exp: 'A prova de que a conversão está certa é sempre a volta: (1 + taxa semestral)² tem de reproduzir a taxa anual.',
    tags: ['taxa-equivalente', 'calculo', 'semestral'],
  }),

  /* ---- c-taxa-real -------------------------------------------------- */
  q('q-tr-01', {
    c: 'c-taxa-real', tipo: 'calculo', dif: 'media',
    hab: 'Calcular a taxa real pela fórmula de Fisher',
    e: 'Uma aplicação rendeu 10% no ano e a inflação do período foi 6%. Qual a taxa real?',
    alt: [
      ['3,77%', true, 'Correta. (1,10 ÷ 1,06) − 1 = 0,0377.'],
      ['4,00%', false, 'É a subtração simples, uma aproximação que sempre superestima o ganho real.'],
      ['4,23%', false, 'Não corresponde a nenhuma das duas operações; parece somar o erro em vez de subtraí-lo.'],
      ['16,60%', false, 'Multiplica os fatores em vez de dividir, tratando a inflação como se fosse rendimento.'],
    ],
    exp: 'Fisher é divisão: (1 + i) ÷ (1 + π) − 1. A subtração é atalho e erra sempre no mesmo sentido.',
    tags: ['taxa-real', 'fisher', 'calculo'],
  }),
  q('q-tr-02', {
    c: 'c-taxa-real', tipo: 'calculo', dif: 'media',
    hab: 'Reconhecer taxa real negativa',
    ctx: 'A poupança de um cliente rendeu 6% em um ano em que o IPCA acumulado foi 10%.',
    e: 'A taxa real do período foi de aproximadamente:',
    alt: [
      ['−3,64%', true, 'Correta. (1,06 ÷ 1,10) − 1 = −0,0364. O poder de compra caiu.'],
      ['−4,00%', false, 'É a subtração simples. O sinal está certo, mas a magnitude está exagerada.'],
      ['+3,64%', false, 'O sinal está invertido: com rendimento abaixo da inflação, a taxa real é negativa.'],
      ['0,00%', false, 'Só seria zero se o rendimento tivesse empatado com a inflação.'],
    ],
    exp: 'Taxa real negativa significa mais reais na conta e menos poder de compra. É o argumento que abre a recomendação de um título IPCA+.',
    tags: ['taxa-real', 'inflacao', 'calculo'],
  }),
  q('q-tr-03', {
    c: 'c-taxa-real', tipo: 'conceitual', dif: 'media',
    hab: 'Avaliar o viés da aproximação por subtração',
    e: 'Em relação ao cálculo correto pela fórmula de Fisher, a aproximação "rendimento menos inflação":',
    alt: [
      ['Superestima sistematicamente o ganho real, e erra mais quanto maior a inflação.', true, 'Correta. O termo desprezado na aproximação é sempre positivo em cenário de inflação positiva.'],
      ['Subestima o ganho real quando a inflação é alta.', false, 'O viés existe, mas é de superestimação — não de subestimação.'],
      ['Acerta sempre, desde que as duas taxas sejam do mesmo período.', false, 'Mesmo com períodos coincidentes a aproximação erra; ela só chega perto quando as taxas são pequenas.'],
      ['Só é válida quando a taxa real resulta negativa.', false, 'A aproximação tem o mesmo viés independentemente do sinal do resultado.'],
    ],
    exp: 'Com 10% e 6% o erro é de 0,23 ponto. Com 100% e 80% passa de 8 pontos. A aproximação falha justamente quando a inflação é o problema.',
    tags: ['taxa-real', 'fisher', 'conceitual'],
  }),
  q('q-tr-04', {
    c: 'c-taxa-real', tipo: 'calculo', dif: 'facil',
    hab: 'Calcular a taxa real em cenário de inflação moderada',
    e: 'Rendimento de 8% ao ano com inflação de 4% no mesmo período produz taxa real de:',
    alt: [
      ['3,85%', true, 'Correta. (1,08 ÷ 1,04) − 1 = 0,0385.'],
      ['4,00%', false, 'Subtração simples. Superestima em 0,15 ponto.'],
      ['12,32%', false, 'Multiplica os fatores; isso somaria a inflação ao rendimento em vez de descontá-la.'],
      ['2,00%', false, 'Divide a diferença pela metade sem base em nenhuma das fórmulas.'],
    ],
    exp: 'Mesmo com inflação moderada a divisão e a subtração divergem. A divergência cresce com a inflação.',
    tags: ['taxa-real', 'fisher', 'calculo'],
  }),
  q('q-tr-05', {
    c: 'c-taxa-real', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Recomendar produto a partir do objetivo de ganho real',
    ctx: 'O cliente afirma que seu objetivo é "não perder para a inflação" em um horizonte de 8 anos.',
    e: 'Qual produto contrata diretamente esse objetivo?',
    alt: [
      ['Um título híbrido atrelado ao IPCA com vencimento próximo ao prazo do objetivo.', true, 'Correta. No IPCA+, a taxa somada ao índice É a taxa real contratada.'],
      ['Um prefixado longo com a maior taxa disponível.', false, 'O prefixado trava a taxa nominal; se a inflação surpreender para cima, o ganho real encolhe.'],
      ['Um pós-fixado ao CDI com liquidez diária.', false, 'Acompanha os juros do país, mas não garante ganho acima da inflação no período.'],
      ['Poupança, por ser isenta de imposto de renda.', false, 'A isenção não impede taxa real negativa, que é exatamente o risco declarado pelo cliente.'],
    ],
    exp: 'O objetivo declarado é ganho REAL. Só a família IPCA+ contrata esse ganho na data da aplicação.',
    tags: ['taxa-real', 'ipca', 'suitability'],
  }),

  /* ---- c-vpl-tir ---------------------------------------------------- */
  q('q-vt-01', {
    c: 'c-vpl-tir', tipo: 'conceitual', dif: 'facil',
    hab: 'Aplicar a regra de decisão do VPL',
    e: 'Um projeto apresenta VPL positivo à taxa de desconto adotada. A decisão indicada é:',
    alt: [
      ['Aceitar, pois o projeto cria valor acima do custo de oportunidade.', true, 'Correta. VPL positivo significa retorno superior à melhor alternativa disponível.'],
      ['Rejeitar, pois o VPL deveria ser zero para haver equilíbrio.', false, 'VPL zero é indiferença, não é o alvo. Positivo é melhor que zero.'],
      ['Aceitar somente se a TIR também for positiva.', false, 'Em projeto convencional, VPL positivo já implica TIR acima do custo de oportunidade.'],
      ['Adiar até que a taxa de desconto caia.', false, 'O projeto já compensa à taxa atual; adiar posterga a criação de valor.'],
    ],
    exp: 'A regra do VPL se decide pelo SINAL. Positivo aceita, negativo rejeita, zero é indiferente.',
    tags: ['vpl', 'decisao', 'conceitual'],
  }),
  q('q-vt-02', {
    c: 'c-vpl-tir', tipo: 'calculo', dif: 'dificil',
    hab: 'Calcular o valor presente líquido de um fluxo',
    ctx: 'Um investimento exige R$ 1.000 hoje e devolve R$ 400, R$ 500 e R$ 600 ao fim de cada um dos três anos seguintes. O custo de oportunidade é 10% ao ano.',
    e: 'O VPL do projeto é de aproximadamente:',
    alt: [
      ['R$ 227,65', true, 'Correta. 400/1,1 + 500/1,21 + 600/1,331 = 1.227,65; menos os 1.000 investidos.'],
      ['R$ 500,00', false, 'É a soma nominal dos fluxos menos o investimento, sem trazer nada a valor presente.'],
      ['R$ 1.227,65', false, 'Esse é o valor presente dos fluxos. Falta descontar o investimento inicial.'],
      ['−R$ 227,65', false, 'O sinal está invertido: os fluxos descontados superam o investimento.'],
    ],
    exp: 'VPL = soma dos fluxos descontados − investimento inicial. Esquecer de abater o investimento é o erro mais comum.',
    tags: ['vpl', 'calculo', 'fluxo-de-caixa'],
  }),
  q('q-vt-03', {
    c: 'c-vpl-tir', tipo: 'conceitual', dif: 'media',
    hab: 'Definir a taxa interna de retorno',
    e: 'A taxa interna de retorno (TIR) de um projeto é:',
    alt: [
      ['A taxa de desconto que faz o VPL ser exatamente zero.', true, 'Correta. É a rentabilidade implícita do fluxo de caixa.'],
      ['A taxa livre de risco vigente na economia.', false, 'Essa é uma referência de mercado, não uma característica do projeto.'],
      ['A razão entre o lucro total e o investimento inicial.', false, 'Isso é retorno sobre investimento, e ignora o momento em que cada fluxo ocorre.'],
      ['A taxa de desconto exigida pelo investidor.', false, 'Essa é o custo de oportunidade, que serve de parâmetro de comparação para a TIR.'],
    ],
    exp: 'A TIR é uma propriedade do fluxo. O custo de oportunidade vem de fora e serve para julgá-la.',
    tags: ['tir', 'conceitual', 'decisao'],
  }),
  q('q-vt-04', {
    c: 'c-vpl-tir', tipo: 'aplicacao', dif: 'media',
    hab: 'Relacionar taxa de desconto e valor presente líquido',
    e: 'Mantido o mesmo fluxo de caixa, um aumento na taxa de desconto adotada produz:',
    alt: [
      ['Redução do VPL, pois os fluxos futuros passam a valer menos hoje.', true, 'Correta. A relação entre taxa de desconto e VPL é inversa.'],
      ['Aumento do VPL, pois o projeto passa a render mais.', false, 'A taxa de desconto não altera o que o projeto rende; altera o quanto exigimos dele.'],
      ['Nenhum efeito, pois o VPL depende só dos fluxos.', false, 'O VPL depende dos fluxos E da taxa usada para trazê-los ao presente.'],
      ['Aumento da TIR do projeto.', false, 'A TIR é determinada pelo fluxo e não se move quando mudamos a taxa de desconto.'],
    ],
    exp: 'Taxa ↑ → denominador maior → valor presente menor → VPL menor. É a mesma mecânica da marcação a mercado.',
    tags: ['vpl', 'taxa-desconto', 'aplicacao'],
  }),
  q('q-vt-05', {
    c: 'c-vpl-tir', tipo: 'calculo', dif: 'media',
    hab: 'Calcular VPL em fluxo de dois períodos',
    ctx: 'Um projeto exige R$ 2.000 hoje e devolve R$ 1.200 no primeiro ano e R$ 1.300 no segundo. O custo de oportunidade é 10% ao ano.',
    e: 'O VPL é de aproximadamente:',
    alt: [
      ['R$ 165,29', true, 'Correta. 1.200/1,1 + 1.300/1,21 = 2.165,29; menos os 2.000 investidos.'],
      ['R$ 500,00', false, 'Soma os fluxos nominalmente (2.500) sem trazer a valor presente.'],
      ['R$ 2.165,29', false, 'É o valor presente dos fluxos; falta abater o investimento inicial.'],
      ['−R$ 165,29', false, 'Sinal invertido: o projeto cria valor, não destrói.'],
    ],
    exp: 'Cada fluxo é descontado pelo número de períodos até ele: o do ano 2 divide por 1,1², não por 1,1.',
    tags: ['vpl', 'calculo', 'fluxo-de-caixa'],
  }),
  q('q-vt-06', {
    c: 'c-vpl-tir', tipo: 'situacao_pratica', dif: 'dificil',
    hab: 'Reconhecer o problema de escala na comparação por TIR',
    ctx: 'Dois projetos mutuamente excludentes: o A investe R$ 100 e tem TIR de 50%; o B investe R$ 100.000 e tem TIR de 15%. O custo de oportunidade é 10%.',
    e: 'A escolha correta e sua justificativa são:',
    alt: [
      ['O B, porque a TIR ignora a escala e o B cria muito mais valor em reais.', true, 'Correta. Entre projetos excludentes, quem decide é o VPL, não a TIR.'],
      ['O A, porque a TIR de 50% é a maior rentabilidade disponível.', false, 'Maior taxa sobre um valor irrelevante cria pouco valor absoluto.'],
      ['Ambos, pois as duas TIRs superam o custo de oportunidade.', false, 'O enunciado diz que são mutuamente excludentes: só um pode ser executado.'],
      ['Nenhum, pois TIR acima de 15% indica risco excessivo.', false, 'TIR alta não é, por si, indicador de risco; e ambas superam o custo de oportunidade.'],
    ],
    exp: 'A TIR é uma taxa e não enxerga tamanho. Quando os dois critérios divergem em projetos excludentes, quem manda é o VPL.',
    tags: ['tir', 'vpl', 'decisao'],
  }),

  /* ---- c-amortizacao ------------------------------------------------ */
  q('q-am-01', {
    c: 'c-amortizacao', tipo: 'comparacao', dif: 'facil',
    hab: 'Comparar a primeira parcela de SAC e Price',
    e: 'Para o mesmo valor financiado, prazo e taxa, a primeira parcela do SAC em relação à do Price é:',
    alt: [
      ['Maior, pois a amortização constante é alta e o saldo devedor ainda está no máximo.', true, 'Correta. A primeira parcela do SAC é sempre a maior da série.'],
      ['Menor, pois o SAC dilui melhor os juros.', false, 'O SAC paga menos juros no TOTAL, mas concentra o pagamento no início.'],
      ['Igual, pois a taxa contratada é a mesma.', false, 'A taxa é a mesma; a distribuição das parcelas ao longo do tempo, não.'],
      ['Depende do valor financiado.', false, 'A relação vale para qualquer valor: o SAC sempre começa mais caro.'],
    ],
    exp: 'SAC começa caro e termina barato; Price é plano. Essa é a pergunta clássica da matéria.',
    tags: ['sac', 'price', 'comparacao'],
  }),
  q('q-am-02', {
    c: 'c-amortizacao', tipo: 'calculo', dif: 'media',
    hab: 'Calcular a primeira parcela no SAC',
    ctx: 'Financiamento de R$ 120.000 em 120 meses pelo SAC, a 1% ao mês.',
    e: 'O valor da primeira parcela é:',
    alt: [
      ['R$ 2.200,00', true, 'Correta. Amortização de R$ 1.000 (120.000 ÷ 120) mais juro de 1% sobre R$ 120.000.'],
      ['R$ 1.000,00', false, 'É só a amortização; falta somar o juro do primeiro mês.'],
      ['R$ 1.200,00', false, 'É só o juro do primeiro mês; falta somar a amortização.'],
      ['R$ 1.721,65', false, 'Esse é o valor da parcela no sistema Price, não no SAC.'],
    ],
    exp: 'Parcela = amortização + juro sobre o saldo devedor. No primeiro mês o saldo ainda é o valor integral financiado.',
    tags: ['sac', 'calculo', 'financiamento'],
  }),
  q('q-am-03', {
    c: 'c-amortizacao', tipo: 'calculo', dif: 'media',
    hab: 'Calcular a primeira parcela no SAC em outro cenário',
    ctx: 'Financiamento de R$ 60.000 em 60 meses pelo SAC, a 1% ao mês.',
    e: 'O valor da primeira parcela é:',
    alt: [
      ['R$ 1.600,00', true, 'Correta. Amortização de R$ 1.000 mais juro de 1% sobre R$ 60.000 (R$ 600).'],
      ['R$ 1.334,67', false, 'Esse é o valor da parcela fixa no sistema Price para o mesmo contrato.'],
      ['R$ 1.010,00', false, 'É a ÚLTIMA parcela do SAC, quando o saldo devedor já caiu para R$ 1.000.'],
      ['R$ 600,00', false, 'É apenas o juro do primeiro mês, sem a amortização.'],
    ],
    exp: 'Repare que a última parcela do SAC (R$ 1.010) fica bem abaixo da parcela fixa do Price: o sistema termina barato.',
    tags: ['sac', 'calculo', 'financiamento'],
  }),
  q('q-am-04', {
    c: 'c-amortizacao', tipo: 'conceitual', dif: 'media',
    hab: 'Descrever a composição da parcela no sistema Price',
    e: 'No sistema Price, ao longo do contrato:',
    alt: [
      ['A parcela é constante, mas a fatia de juros diminui e a de amortização cresce.', true, 'Correta. Como o saldo devedor cai, o juro sobre ele cai, e a amortização ocupa o espaço liberado.'],
      ['Tanto a parcela quanto a fatia de juros permanecem constantes.', false, 'Só a parcela é constante; sua composição interna muda todo mês.'],
      ['A parcela é constante e a amortização também.', false, 'Amortização constante é a definição do SAC, não do Price.'],
      ['A parcela cresce, acompanhando a amortização.', false, 'A parcela constante é a característica que dá nome ao sistema.'],
    ],
    exp: 'Parcela fixa não significa juro fixo em reais. No começo ela é quase toda juro; no fim, quase toda amortização.',
    tags: ['price', 'amortizacao', 'conceitual'],
  }),
  q('q-am-05', {
    c: 'c-amortizacao', tipo: 'comparacao', dif: 'media',
    hab: 'Comparar o custo total de juros entre os sistemas',
    ctx: 'Financiamento de R$ 120.000 em 120 meses a 1% ao mês. No SAC os juros totais somam R$ 72.600; no Price, R$ 86.598.',
    e: 'A explicação para a diferença é que o SAC:',
    alt: [
      ['Amortiza mais rápido no início, então o saldo devedor sobre o qual o juro incide cai antes.', true, 'Correta. Juro incide sobre saldo devedor: quem reduz o saldo mais cedo paga menos juro.'],
      ['Cobra uma taxa de juros menor que o Price.', false, 'A taxa contratada é a mesma nos dois sistemas — 1% ao mês.'],
      ['Tem prazo menor que o Price.', false, 'O prazo é idêntico: 120 meses nos dois casos.'],
      ['Isenta o cliente dos juros das últimas parcelas.', false, 'Não há isenção; o juro da última parcela do SAC é apenas pequeno, porque o saldo é pequeno.'],
    ],
    exp: 'Mesma taxa, mesmo prazo, custo diferente. O que muda é a velocidade com que o saldo devedor é reduzido.',
    tags: ['sac', 'price', 'juros-totais'],
  }),
  q('q-am-06', {
    c: 'c-amortizacao', tipo: 'situacao_pratica', dif: 'dificil',
    hab: 'Recomendar o sistema conforme a capacidade de pagamento',
    ctx: 'O cliente tem renda apertada hoje, mas espera crescimento salarial. Ele pergunta qual sistema escolher no financiamento do imóvel.',
    e: 'A orientação tecnicamente correta é:',
    alt: [
      ['Apresentar o trade-off: o Price cabe melhor no orçamento inicial, mas custa mais juros no total que o SAC.', true, 'Correta. A decisão depende da capacidade de pagamento hoje, e o dever é explicitar o custo dessa escolha.'],
      ['Recomendar o SAC sem ressalvas, por ser o mais barato no total.', false, 'O SAC exige parcela inicial mais alta, o que pode não caber na renda comprovada.'],
      ['Recomendar o Price sem ressalvas, por ter parcela menor.', false, 'Omitir que o custo total é maior é omitir informação relevante para a decisão.'],
      ['Afirmar que os dois sistemas custam o mesmo, pois a taxa é igual.', false, 'Taxa igual não significa custo igual: o total de juros difere pela velocidade de amortização.'],
    ],
    exp: 'Não existe sistema melhor em abstrato. Existe o que cabe no orçamento — e o dever de dizer quanto essa escolha custa.',
    tags: ['sac', 'price', 'atendimento'],
  }),

  /* ---- c-duration ---------------------------------------------------- */
  q('q-du-01', {
    c: 'c-duration', tipo: 'conceitual', dif: 'facil',
    hab: 'Identificar a duration de um título zero cupom',
    e: 'A duration de um título zero cupom com vencimento em 5 anos é:',
    alt: [
      ['Exatamente 5 anos, pois todo o fluxo ocorre no vencimento.', true, 'Correta. Sem pagamentos intermediários, o prazo médio ponderado é o próprio prazo.'],
      ['Menor que 5 anos, pois a duration é sempre inferior ao prazo.', false, 'Isso vale para títulos COM cupom. No zero cupom as duas medidas coincidem.'],
      ['Maior que 5 anos, por causa da capitalização dos juros.', false, 'A duration nunca ultrapassa o prazo até o vencimento.'],
      ['Indeterminada sem conhecer a taxa contratada.', false, 'No zero cupom a duration independe da taxa: há um único fluxo, e ele define a média.'],
    ],
    exp: 'Zero cupom é o único caso em que duration e prazo até o vencimento são o mesmo número.',
    tags: ['duration', 'zero-cupom', 'conceitual'],
  }),
  q('q-du-02', {
    c: 'c-duration', tipo: 'calculo', dif: 'media',
    hab: 'Estimar a variação de preço a partir da duration modificada',
    ctx: 'Um título tem duration modificada de 4,09.',
    e: 'Diante de uma alta de 1 ponto percentual na taxa de juros, o preço tende a:',
    alt: [
      ['Cair cerca de 4,09%.', true, 'Correta. Variação do preço ≈ − duration modificada × variação da taxa.'],
      ['Cair cerca de 1%.', false, 'Confunde a variação da TAXA com a variação do PREÇO; a duration é justamente o multiplicador entre elas.'],
      ['Subir cerca de 4,09%.', false, 'O sinal está invertido: juros sobem, preço cai.'],
      ['Permanecer estável, pois a duration mede prazo e não preço.', false, 'Duration mede prazo médio E, por isso mesmo, sensibilidade de preço.'],
    ],
    exp: 'A duration modificada é o fator de conversão entre variação de taxa e variação percentual de preço.',
    tags: ['duration', 'sensibilidade', 'calculo'],
  }),
  q('q-du-03', {
    c: 'c-duration', tipo: 'comparacao', dif: 'media',
    hab: 'Comparar a duration de títulos com e sem cupom',
    ctx: 'Dois títulos vencem em 5 anos: um paga cupons semestrais e o outro é zero cupom.',
    e: 'Sobre a duration dos dois, é correto afirmar:',
    alt: [
      ['A do título com cupom é menor, porque parte do dinheiro retorna antes do vencimento.', true, 'Correta. Os cupons antecipam fluxos e puxam a média de prazo para baixo.'],
      ['A do título com cupom é maior, porque há mais pagamentos.', false, 'O número de pagamentos não aumenta o prazo médio; antecipar caixa o reduz.'],
      ['As durations são iguais, porque o vencimento é o mesmo.', false, 'Vencimento igual não implica duration igual — é justamente essa a distinção da matéria.'],
      ['A comparação depende do emissor de cada título.', false, 'Duration é função do fluxo de caixa e da taxa, não da qualidade de crédito do emissor.'],
    ],
    exp: 'É por isso que dois títulos com o mesmo vencimento podem oscilar de forma bem diferente numa mudança de juros.',
    tags: ['duration', 'cupom', 'comparacao'],
  }),
  q('q-du-04', {
    c: 'c-duration', tipo: 'aplicacao', dif: 'media',
    hab: 'Identificar os fatores que aumentam a duration',
    e: 'Mantidos os demais fatores constantes, a duration de um título AUMENTA quando:',
    alt: [
      ['O prazo até o vencimento aumenta.', true, 'Correta. Prazo maior empurra os fluxos para longe e eleva o prazo médio ponderado.'],
      ['O cupom pago aumenta.', false, 'Cupom maior antecipa caixa e REDUZ a duration.'],
      ['A frequência de pagamento dos cupons aumenta.', false, 'Pagar mais vezes antecipa caixa e reduz a duration.'],
      ['A taxa de juros de mercado aumenta.', false, 'Taxa maior desconta mais os fluxos distantes, reduzindo o peso deles — e a duration.'],
    ],
    exp: 'Prazo longo e cupom pequeno é a combinação de maior sensibilidade a juros em renda fixa.',
    tags: ['duration', 'sensibilidade', 'aplicacao'],
  }),
  q('q-du-05', {
    c: 'c-duration', tipo: 'situacao_pratica', dif: 'dificil',
    hab: 'Recomendar o alongamento ou encurtamento da carteira',
    ctx: 'Um cliente conservador reclama da oscilação diária dos títulos públicos que possui e diz que não tolera ver o saldo cair.',
    e: 'A providência tecnicamente adequada é:',
    alt: [
      ['Reduzir a duration da carteira, migrando para títulos mais curtos ou pós-fixados.', true, 'Correta. Menor duration significa menor sensibilidade a variações de taxa.'],
      ['Alongar os vencimentos para diluir a oscilação no tempo.', false, 'Alongar aumenta a duration e, com ela, a oscilação — o oposto do pedido.'],
      ['Manter a carteira e explicar que a oscilação não é real.', false, 'A oscilação é real e se materializa em perda se houver resgate antecipado.'],
      ['Trocar por títulos de emissor privado com taxa maior.', false, 'Isso troca risco de mercado por risco de crédito, sem resolver a oscilação.'],
    ],
    exp: 'Tolerância baixa a oscilação é um problema de duration. Pós-fixados atrelados à Selic são o instrumento de menor sensibilidade.',
    tags: ['duration', 'suitability', 'renda-fixa'],
  }),
  q('q-du-06', {
    c: 'c-duration', tipo: 'calculo', dif: 'dificil',
    hab: 'Converter duration em duration modificada',
    ctx: 'Um título tem duration de 6 anos e a taxa de juros de mercado é de 12% ao ano.',
    e: 'A duration modificada e o efeito de uma alta de 0,5 ponto percentual na taxa são, respectivamente:',
    alt: [
      ['5,36 e queda de aproximadamente 2,68% no preço.', true, 'Correta. Dmod = 6 ÷ 1,12 = 5,36; e 5,36 × 0,5 = 2,68%.'],
      ['6,00 e queda de aproximadamente 3,00% no preço.', false, 'Usa a duration sem dividir por (1 + i); esquece a conversão para duration modificada.'],
      ['5,36 e queda de aproximadamente 5,36% no preço.', false, 'A duration modificada está certa, mas foi multiplicada por 1 ponto e não por 0,5.'],
      ['6,72 e queda de aproximadamente 3,36% no preço.', false, 'Multiplica por (1 + i) em vez de dividir, invertendo a operação.'],
    ],
    exp: 'São dois passos: converter a duration em modificada dividindo por (1 + i), e só então multiplicar pela variação da taxa.',
    tags: ['duration', 'calculo', 'sensibilidade'],
  }),
]
