import { q } from './builder'

/** Questões autorais — Macrotema 1 (SFN e PLD). */
export const BANCO_M1 = [
  q('q-cmn-01', {
    c: 'c-cmn', tipo: 'conceitual', dif: 'facil',
    hab: 'Identificar a natureza normativa do CMN',
    e: 'O Conselho Monetário Nacional (CMN) é caracterizado como órgão:',
    alt: [
      ['Normativo, responsável por fixar as diretrizes das políticas monetária, creditícia e cambial.', true, 'Correta. O CMN é o órgão máximo e exclusivamente normativo do SFN.'],
      ['Supervisor, responsável por fiscalizar as instituições financeiras.', false, 'Quem fiscaliza são BACEN, CVM, SUSEP e PREVIC. O CMN não fiscaliza.'],
      ['Executor, responsável por conduzir as operações de mercado aberto.', false, 'Operações de mercado aberto são executadas pelo Banco Central.'],
      ['Autorregulador, responsável por editar códigos de melhores práticas.', false, 'Autorregulação é papel de entidades como a ANBIMA, não do CMN.'],
    ],
    exp: 'O CMN normatiza; os supervisores fiscalizam e o BACEN executa. Essa separação é a base do bloco de SFN.',
    tags: ['cmn', 'sfn', 'orgaos'],
  }),
  q('q-cmn-02', {
    c: 'c-cmn', tipo: 'multipla_escolha', dif: 'media',
    hab: 'Reconhecer a composição do CMN',
    e: 'O CMN é composto por:',
    alt: [
      ['Ministro da Fazenda, Ministro do Planejamento e Presidente do Banco Central.', true, 'Correta. São três membros, e o Ministro da Fazenda preside o conselho.'],
      ['Presidente do Banco Central, Presidente da CVM e Ministro da Fazenda.', false, 'A CVM não integra o CMN.'],
      ['Presidente da República, Ministro da Fazenda e Presidente do Banco Central.', false, 'O Presidente da República não integra o conselho.'],
      ['Apenas o Ministro da Fazenda e o Presidente do Banco Central.', false, 'Falta o Ministro do Planejamento — são três membros, não dois.'],
    ],
    exp: 'Três membros: Fazenda (que preside), Planejamento e BACEN. A banca costuma trocar um deles.',
    tags: ['cmn', 'composicao'],
  }),
  q('q-cmn-03', {
    c: 'c-cmn', tipo: 'comparacao', dif: 'media',
    hab: 'Distinguir quem define meta de inflação de quem define a Selic',
    e: 'Sobre a meta de inflação e a taxa Selic, é correto afirmar que:',
    alt: [
      ['A meta de inflação é definida pelo CMN e a meta da Selic pelo Copom.', true, 'Correta. São decisões de órgãos distintos: o CMN fixa o alvo, o Copom escolhe o instrumento.'],
      ['Ambas são definidas pelo Copom.', false, 'O Copom define apenas a meta da Selic.'],
      ['Ambas são definidas pelo CMN.', false, 'O CMN não define a taxa Selic.'],
      ['A meta de inflação é definida pelo IBGE, que calcula o IPCA.', false, 'O IBGE calcula o índice, mas não define a meta.'],
    ],
    exp: 'CMN define o destino (meta de inflação). Copom escolhe a velocidade (Selic) para chegar lá.',
    tags: ['cmn', 'copom', 'inflacao'],
  }),
  q('q-bacen-01', {
    c: 'c-bacen', tipo: 'conceitual', dif: 'facil',
    hab: 'Identificar os instrumentos de política monetária',
    e: 'São instrumentos clássicos de política monetária do Banco Central:',
    alt: [
      ['Taxa Selic, depósito compulsório e operações de mercado aberto.', true, 'Correta. O redesconto complementa, atuando como socorro de liquidez.'],
      ['Taxa Selic, imposto de renda e depósito compulsório.', false, 'Imposto de renda é política fiscal, não monetária.'],
      ['Superávit primário, câmbio flutuante e taxa Selic.', false, 'Superávit primário é política fiscal.'],
      ['Salário mínimo, taxa Selic e crédito consignado.', false, 'Salário mínimo e consignado não são instrumentos de política monetária.'],
    ],
    exp: 'Política monetária mexe na quantidade de moeda e no custo do dinheiro. Tributos e gastos são política fiscal.',
    tags: ['bacen', 'politica-monetaria'],
  }),
  q('q-bacen-02', {
    c: 'c-bacen', tipo: 'aplicacao', dif: 'media',
    hab: 'Prever o efeito de uma medida contracionista',
    e: 'Para conter uma inflação acima da meta, o Banco Central pode:',
    alt: [
      ['Elevar a taxa Selic e aumentar o depósito compulsório.', true, 'Correta. Ambas retiram estímulo da economia e reduzem a pressão sobre os preços.'],
      ['Reduzir a taxa Selic e comprar títulos no mercado aberto.', false, 'Essas medidas são expansionistas — aumentariam a pressão inflacionária.'],
      ['Reduzir o depósito compulsório e ampliar o redesconto.', false, 'Ambas injetam liquidez, o oposto do desejado.'],
      ['Aumentar os gastos públicos.', false, 'Gasto público é política fiscal, e nesse caso expansionista.'],
    ],
    exp: 'Contracionista = tirar dinheiro de circulação. Selic sobe, compulsório sobe, BC vende títulos.',
    tags: ['bacen', 'politica-monetaria', 'inflacao'],
  }),
  q('q-bacen-03', {
    c: 'c-bacen', tipo: 'conceitual', dif: 'dificil',
    hab: 'Diferenciar Selic meta de Selic over',
    e: 'A diferença entre a Selic meta e a Selic over é que:',
    alt: [
      ['A meta é definida pelo Copom; a over é a taxa efetivamente praticada nas operações compromissadas com títulos públicos.', true, 'Correta. A over gravita em torno da meta, mas é resultado de mercado.'],
      ['A meta é diária e a over é anual.', false, 'Ambas são expressas em termos anuais; a diferença não é de periodicidade.'],
      ['A over é definida pelo CMN e a meta pelo Copom.', false, 'O CMN não define nenhuma das duas.'],
      ['São sinônimos, usados indistintamente.', false, 'Não são sinônimos: uma é decisão, a outra é resultado observado.'],
    ],
    exp: 'Meta é decisão de política. Over é o que o mercado efetivamente praticou. Elas convergem, mas não são a mesma coisa.',
    tags: ['bacen', 'selic'],
  }),
  q('q-cvm-01', {
    c: 'c-cvm', tipo: 'multipla_escolha', dif: 'facil',
    hab: 'Associar produto ao supervisor correto',
    e: 'A fiscalização dos fundos de investimento cabe à:',
    alt: [
      ['CVM', true, 'Correta. Cotas de fundo são valores mobiliários, campo da CVM.'],
      ['SUSEP', false, 'A SUSEP cuida de seguros, capitalização e previdência aberta.'],
      ['PREVIC', false, 'A PREVIC cuida apenas da previdência complementar fechada.'],
      ['BACEN', false, 'O BACEN supervisiona instituições financeiras, não o fundo em si.'],
    ],
    exp: 'Fundo de investimento é valor mobiliário. Valor mobiliário é CVM.',
    tags: ['cvm', 'supervisores', 'fundos'],
  }),
  q('q-cvm-02', {
    c: 'c-cvm', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Encaminhar demanda ao supervisor correto',
    ctx: 'Um cliente procura o gerente com três reclamações: sobre o fundo de ações que contratou, sobre o VGBL do banco e sobre o fundo de pensão da empresa onde trabalha.',
    e: 'Os supervisores competentes para cada reclamação são, respectivamente:',
    alt: [
      ['CVM, SUSEP e PREVIC.', true, 'Correta. Fundo é CVM; VGBL é previdência aberta (SUSEP); fundo de pensão é previdência fechada (PREVIC).'],
      ['CVM, PREVIC e SUSEP.', false, 'Inverteu: VGBL é aberta (SUSEP) e fundo de pensão é fechada (PREVIC).'],
      ['BACEN, SUSEP e PREVIC.', false, 'Fundo de investimento é competência da CVM, não do BACEN.'],
      ['CVM, CVM e PREVIC.', false, 'VGBL é produto de previdência aberta, supervisionado pela SUSEP.'],
    ],
    exp: 'As palavras "aberta" e "fechada" decidem entre SUSEP e PREVIC. Fundo de investimento é sempre CVM.',
    tags: ['supervisores', 'previdencia', 'cvm'],
  }),
  q('q-cvm-03', {
    c: 'c-cvm', tipo: 'comparacao', dif: 'dificil',
    hab: 'Separar previdência aberta de fechada',
    e: 'A diferença essencial entre previdência complementar aberta e fechada é que:',
    alt: [
      ['A aberta pode ser contratada por qualquer pessoa e é supervisionada pela SUSEP; a fechada é restrita a um grupo e supervisionada pela PREVIC.', true, 'Correta. O critério é o acesso, e o supervisor decorre dele.'],
      ['A aberta é isenta de imposto de renda e a fechada não.', false, 'A isenção não é o critério de distinção; ambas são tributadas conforme regime escolhido.'],
      ['A aberta é garantida pelo FGC e a fechada não.', false, 'Nenhuma das duas tem cobertura do FGC.'],
      ['A aberta é supervisionada pela CVM e a fechada pela SUSEP.', false, 'Nenhuma das duas é supervisionada pela CVM.'],
    ],
    exp: 'Aberta = qualquer um contrata = SUSEP. Fechada = só quem pertence ao grupo = PREVIC.',
    tags: ['previdencia', 'supervisores'],
  }),
  q('q-pld-01', {
    c: 'c-pld', tipo: 'conceitual', dif: 'facil',
    hab: 'Ordenar as etapas da lavagem de dinheiro',
    e: 'As etapas da lavagem de dinheiro, na ordem correta, são:',
    alt: [
      ['Colocação, ocultação e integração.', true, 'Correta. É a sequência clássica adotada pela regulação.'],
      ['Ocultação, colocação e integração.', false, 'A colocação vem primeiro: é a entrada do recurso no sistema financeiro.'],
      ['Integração, colocação e ocultação.', false, 'A integração é a última etapa, não a primeira.'],
      ['Colocação, integração e ocultação.', false, 'A ocultação vem antes da integração.'],
    ],
    exp: 'Coloca no sistema, embaralha o rastro, devolve com aparência lícita. Nessa ordem.',
    tags: ['pld', 'lavagem'],
  }),
  q('q-pld-02', {
    c: 'c-pld', tipo: 'situacao_pratica', dif: 'media',
    hab: 'Aplicar o dever de comunicação ao COAF',
    ctx: 'Um cliente com renda declarada de R$ 4.000 mensais passa a realizar depósitos em espécie de R$ 35.000 por semana, sem apresentar justificativa compatível.',
    e: 'A conduta correta do profissional é:',
    alt: [
      ['Comunicar a operação ao COAF, sem dar ciência ao cliente.', true, 'Correta. Basta o indício, e a comunicação é sigilosa.'],
      ['Informar o cliente de que a operação será comunicada ao COAF.', false, 'Dar ciência ao cliente é vedado e compromete a investigação.'],
      ['Aguardar que o valor acumulado ultrapasse R$ 1 milhão antes de comunicar.', false, 'Não existe esse piso; o critério é a incompatibilidade e o indício.'],
      ['Encerrar a conta e não comunicar, pois o vínculo terminou.', false, 'Encerrar a conta não afasta o dever de comunicar.'],
    ],
    exp: 'Movimentação incompatível com a renda é sinal de alerta clássico. Comunica-se o indício, em sigilo.',
    tags: ['pld', 'coaf', 'conduta'],
  }),
  q('q-pld-03', {
    c: 'c-pld', tipo: 'verdadeiro_falso', dif: 'facil',
    hab: 'Avaliar afirmações sobre PLD',
    e: 'Avalie: "A comunicação de operação suspeita ao COAF depende de autorização judicial prévia."',
    alt: [
      ['Falso — a comunicação é obrigação administrativa e independe de decisão judicial.', true, 'Correta. O dever nasce da regulação, não de ordem judicial.'],
      ['Verdadeiro — sem ordem judicial há quebra de sigilo bancário.', false, 'A comunicação ao COAF é exceção legal ao sigilo, prevista na própria lei.'],
      ['Verdadeiro — apenas para valores acima do limite regulatório.', false, 'Não há exigência de autorização judicial em nenhuma faixa de valor.'],
      ['Falso — mas somente quando o cliente autoriza expressamente.', false, 'A autorização do cliente não é requisito; ele nem deve ser informado.'],
    ],
    exp: 'A lei de PLD cria uma exceção ao sigilo. A comunicação é dever direto da instituição.',
    tags: ['pld', 'coaf', 'sigilo'],
  }),
  q('q-pld-04', {
    c: 'c-pld', tipo: 'arvore_decisao', dif: 'dificil',
    hab: 'Conduzir um atendimento com indício de lavagem',
    ctx: 'Cliente antigo, perfil conservador, aparece na agência querendo aplicar R$ 300.000 em espécie, trazidos em uma sacola, e pede que a operação seja feita "sem muito registro".',
    e: 'Primeira decisão: qual é a conduta inicial correta?',
    alt: [
      ['Recusar o atendimento informal, exigir identificação da origem dos recursos e seguir o procedimento interno de PLD.', true, 'Correta. Origem dos recursos e formalização são pré-requisitos, não etapas opcionais.'],
      ['Aceitar o depósito e analisar depois, para não constranger um cliente antigo.', false, 'Relacionamento antigo não afasta o dever de diligência; aceitar primeiro agrava o risco.'],
      ['Orientar o cliente a fracionar em depósitos menores para evitar burocracia.', false, 'Orientar o fracionamento é conduta gravíssima — ajuda a estruturar a lavagem.'],
      ['Encaminhar o cliente a outra agência.', false, 'Transferir o problema não cumpre o dever de comunicar nem o de diligenciar.'],
    ],
    exp: 'Espécie em volume atípico + pedido de informalidade = dois sinais de alerta somados. O procedimento formal é inegociável.',
    tags: ['pld', 'conduta', 'coaf'],
    passos: [
      {
        id: 'p2',
        enunciado: 'O cliente não comprova a origem e insiste. Qual o próximo passo?',
        alternativas: [
          { id: 'p2-a', texto: 'Comunicar ao COAF e registrar internamente, sem informar o cliente.', correta: true, justificativa: 'Correta. A recusa em comprovar origem reforça o indício e aciona o dever de comunicar.' },
          { id: 'p2-b', texto: 'Realizar a operação e anotar a ressalva no cadastro.', correta: false, justificativa: 'Anotar ressalva não substitui a comunicação e ainda concretiza a operação suspeita.' },
          { id: 'p2-c', texto: 'Informar o cliente de que ele será comunicado ao COAF.', correta: false, justificativa: 'Dar ciência ao cliente é vedado.' },
        ],
        desdobramento: 'A recusa em comprovar a origem transforma a suspeita em indício concreto.',
      },
    ],
  }),
] as const
